In [2]:
import torch

from torch import nn

import torch.nn.utils.prune as prune
import torch.nn.functional as F

from models import get_model

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
model = get_model("mobilenet", 2, True)
model.to(DEVICE)

MobileNetV2(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU6(inplace=True)
    )
    (1): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU6(inplace=True)
        )
        (1): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (2): InvertedResidual(
      (conv): Sequential(
        (0): Conv2dNormActivation(
          (0): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (1): BatchNorm2d(96, eps=

In [10]:
module = model.features[-1][0]

print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 0.0456]],

         [[ 0.0229]],

         [[-0.0672]],

         ...,

         [[ 0.0022]],

         [[-0.0020]],

         [[-0.1942]]],


        [[[ 0.0343]],

         [[-0.0669]],

         [[ 0.0341]],

         ...,

         [[-0.0340]],

         [[-0.0280]],

         [[ 0.0235]]],


        [[[ 0.0421]],

         [[ 0.0051]],

         [[ 0.0335]],

         ...,

         [[-0.0326]],

         [[ 0.0287]],

         [[ 0.0018]]],


        ...,


        [[[ 0.0238]],

         [[ 0.0562]],

         [[ 0.0086]],

         ...,

         [[-0.0420]],

         [[ 0.0155]],

         [[-0.0487]]],


        [[[ 0.0202]],

         [[ 0.0903]],

         [[-0.0486]],

         ...,

         [[ 0.0016]],

         [[-0.0266]],

         [[ 0.0428]]],


        [[[-0.0438]],

         [[-0.0728]],

         [[-0.0009]],

         ...,

         [[ 0.0581]],

         [[-0.0106]],

         [[ 0.0109]]]], device='cuda:0'))]


In [11]:
print(list(module.named_buffers()))

[]


In [12]:
prune.random_unstructured(module, name="weight", amount=0.3)

Conv2d(320, 1280, kernel_size=(1, 1), stride=(1, 1), bias=False)

In [14]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 0.0456]],

         [[ 0.0229]],

         [[-0.0672]],

         ...,

         [[ 0.0022]],

         [[-0.0020]],

         [[-0.1942]]],


        [[[ 0.0343]],

         [[-0.0669]],

         [[ 0.0341]],

         ...,

         [[-0.0340]],

         [[-0.0280]],

         [[ 0.0235]]],


        [[[ 0.0421]],

         [[ 0.0051]],

         [[ 0.0335]],

         ...,

         [[-0.0326]],

         [[ 0.0287]],

         [[ 0.0018]]],


        ...,


        [[[ 0.0238]],

         [[ 0.0562]],

         [[ 0.0086]],

         ...,

         [[-0.0420]],

         [[ 0.0155]],

         [[-0.0487]]],


        [[[ 0.0202]],

         [[ 0.0903]],

         [[-0.0486]],

         ...,

         [[ 0.0016]],

         [[-0.0266]],

         [[ 0.0428]]],


        [[[-0.0438]],

         [[-0.0728]],

         [[-0.0009]],

         ...,

         [[ 0.0581]],

         [[-0.0106]],

         [[ 0.0109]]]], device='cuda:0'))

In [15]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[1.]],

         [[1.]],

         [[1.]],

         ...,

         [[1.]],

         [[0.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[0.]],

         ...,

         [[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]],

         ...,

         [[1.]],

         [[0.]],

         [[1.]]],


        ...,


        [[[1.]],

         [[1.]],

         [[1.]],

         ...,

         [[1.]],

         [[1.]],

         [[1.]]],


        [[[0.]],

         [[0.]],

         [[1.]],

         ...,

         [[0.]],

         [[1.]],

         [[1.]]],


        [[[0.]],

         [[1.]],

         [[1.]],

         ...,

         [[1.]],

         [[1.]],

         [[0.]]]], device='cuda:0'))]


In [16]:
print(module.weight)

tensor([[[[ 0.0456]],

         [[ 0.0229]],

         [[-0.0672]],

         ...,

         [[ 0.0022]],

         [[-0.0000]],

         [[-0.1942]]],


        [[[ 0.0343]],

         [[-0.0669]],

         [[ 0.0000]],

         ...,

         [[-0.0340]],

         [[-0.0280]],

         [[ 0.0235]]],


        [[[ 0.0421]],

         [[ 0.0051]],

         [[ 0.0335]],

         ...,

         [[-0.0326]],

         [[ 0.0000]],

         [[ 0.0018]]],


        ...,


        [[[ 0.0238]],

         [[ 0.0562]],

         [[ 0.0086]],

         ...,

         [[-0.0420]],

         [[ 0.0155]],

         [[-0.0487]]],


        [[[ 0.0000]],

         [[ 0.0000]],

         [[-0.0486]],

         ...,

         [[ 0.0000]],

         [[-0.0266]],

         [[ 0.0428]]],


        [[[-0.0000]],

         [[-0.0728]],

         [[-0.0009]],

         ...,

         [[ 0.0581]],

         [[-0.0106]],

         [[ 0.0000]]]], device='cuda:0')


In [17]:
print(module._forward_pre_hooks)

OrderedDict([(0, <torch.nn.utils.prune.RandomUnstructured object at 0x71ef0eeadb80>)])


In [18]:
model.state_dict().keys()

odict_keys(['features.0.0.weight', 'features.0.1.weight', 'features.0.1.bias', 'features.0.1.running_mean', 'features.0.1.running_var', 'features.0.1.num_batches_tracked', 'features.1.conv.0.0.weight', 'features.1.conv.0.1.weight', 'features.1.conv.0.1.bias', 'features.1.conv.0.1.running_mean', 'features.1.conv.0.1.running_var', 'features.1.conv.0.1.num_batches_tracked', 'features.1.conv.1.weight', 'features.1.conv.2.weight', 'features.1.conv.2.bias', 'features.1.conv.2.running_mean', 'features.1.conv.2.running_var', 'features.1.conv.2.num_batches_tracked', 'features.2.conv.0.0.weight', 'features.2.conv.0.1.weight', 'features.2.conv.0.1.bias', 'features.2.conv.0.1.running_mean', 'features.2.conv.0.1.running_var', 'features.2.conv.0.1.num_batches_tracked', 'features.2.conv.1.0.weight', 'features.2.conv.1.1.weight', 'features.2.conv.1.1.bias', 'features.2.conv.1.1.running_mean', 'features.2.conv.1.1.running_var', 'features.2.conv.1.1.num_batches_tracked', 'features.2.conv.2.weight', 'fea